version: '2'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - "7070:7070"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: "4.0"
      EDDI_ENV: production
  mongodb:
    image: mongo:3
    #ports:       #see override in your own repository with docker-compose.override.yml on each deployed machine for CRITICAL DATA
    volumes_from:
        - mongodata       #see override in your own repositorywith  docker-compose.override.yml on each deployed machine for CRITICAL DATA
    restart: always
  mongodata:
    image: alpine
    volumes:
      - "/persistence/eddimongodb:/data/db"
    command: echo Persistence for Mongo
